version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: flearn_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: flearn_db
      POSTGRES_USER: flearn_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - flearn_network

  # pgAdmin for PostgreSQL management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: flearn_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@flearn.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
      PGADMIN_LISTEN_PORT: 80
    secrets:
      - pgadmin_password
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - flearn_network

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: flearn_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: flearn_admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_password
      MONGO_INITDB_DATABASE: flearn_mongo_db
    secrets:
      - mongo_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - flearn_network

  # MongoDB Express (Web-based MongoDB admin interface)
  mongo-express:
    image: mongo-express:latest
    container_name: flearn_mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: flearn_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo_password
      ME_CONFIG_MONGODB_URL: mongodb://flearn_admin:flearn_mongo_password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/mongo_express_password
    secrets:
      - mongo_password
      - mongo_express_password
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - flearn_network

# Named volumes for data persistence
volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  mongodb_data:
    driver: local

# Docker secrets for secure password management
secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt
  mongo_password:
    file: ./secrets/mongo_password.txt
  mongo_express_password:
    file: ./secrets/mongo_express_password.txt

# Custom network
networks:
  flearn_network:
    driver: bridge
